[package]

name = "mcp"
version = "0.2.0"
authors = ["Alvaro Polo <apoloval@gmail.com>"]

[dependencies]
byteorder = "0.5"
docopt = "0.6"
rustc-serialize = "0.3"

[dev-dependencies]
quickcheck = "0.2"

[[bin]]
name = "mcp"
path = "src/bin/main.rs"
