[package]

name = "mcp"
version = "0.2.0"
authors = ["Alvaro Polo <apoloval@gmail.com>"]

[dependencies]
byteorder = "*"
docopt = "*"
rustc-serialize = "*"

[dev-dependencies]
quickcheck = "*"

[[bin]]
name = "mcp"
path = "src/bin/main.rs"
